# baseurl: "http://www.dublincore.org"
uglyURLs: false
# canonifyURLs: false
# relativeURLs: false
ignoreFiles: []
languageCode: "en-gb"
# title: "The Home of the Dublin Core Metadata Initiative"
title: "COAR Next Generation Repositories"
author: ""
metaDataFormat: "yaml"
publishdir: ""
theme: "coar_ngr"
permalinks:
  # news: /news/:year/:month/:day/:title
  # page: /:title/
params:
  # tagline: "community, metadata, innovation"
  # tagline: "supporting innovation in metadata design, implementation & best practices"
  tagline: "Defining the next generation repository"
# taxonomies:
#   technology: "technologies"
blackfriday:
  smartypants: false
disablePathToLower: true
